version: "3"
services: 
    app:
        build: .
        image: epam-laravel-app
        container_name: epam-laravel-app
        sysctls:
            - net.ipv4.ip_unprivileged_port_start=0
        depends_on:
            - database
            - redis
        ports:
            - "8080:8080"
        links:
            - database:database
            - redis:redis
        volumes:
            - .:/srv/app
        env_file: .docker.env
        environment:
            CONTAINER_ROLE: app
            CONTAINER_ENV: local

    database:
        container_name: epam-db
        image: mysql:5.7
        ports:
            - "13309:3306"
        volumes:
            - .docker/mysql/data:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=epam
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=epam
            - MYSQL_PASSWORD=password
    redis:
        container_name: epam-redis
        image: centos/redis-5-centos7
        ports:
            - "6379:6379"
        environment:
            - REDIS_PASSWORD=beans
    artisan:
        image: epam-laravel-app
        container_name: epam-artisan
        volumes:
            - .:/srv/app
        entrypoint: [
            "php",
            "/srv/app/artisan"
        ]
        environment:
            CONTAINER_ROLE: artisan
            CONTAINER_ENV: local

    scheduler:
        image: epam-laravel-app
        container_name: epam-scheduler
        sysctls: 
            - net.ipv4.ip_unprivileged_port_start=0
        depends_on: 
            - app
        volumes:
            - .:/srv/app
        environment:
            CONTAINER_ROLE: scheduler
            CONTAINER_ENV: local

    queue:
        image: epam-laravel-app
        container_name: epam-queue
        sysctls: 
            - net.ipv4.ip_unprivileged_port_start=0
        depends_on: 
            - app
        volumes:
            - .:/srv/app
        environment:
            CONTAINER_ROLE: queue
            CONTAINER_ENV: local        
        