version: "3"
services:
    db:
        container_name: ${DOCKER_NAME:-gpm}-db
        image: mysql:8.0
        ports:
            - "13309:3306"
        volumes:
            - db:/var/lib/mysql
            - .docker/mysql/db-init:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_SORT_BUFFER_SIZE=256000000
        user: ${DOCKER_USER:-501:20}

    app:
        build: .
        image: ${DOCKER_NAME:-gpm}-app
        container_name: ${DOCKER_NAME:-gpm}-app
        entrypoint:
            - bash
            - -c
            - |-
                php artisan serve -vvv --host 0.0.0.0 --port "${APP_PORT:-8013}"
        depends_on:
            - db
            - redis
        ports:
            - "${APP_PORT:-8013}:${APP_PORT:-8013}"
            - "9000:9000"
        links:
            - db:db
            - redis:redis
        volumes:
            - .:/srv/app
        environment:
            DB_HOST: ${DOCKER_NAME:-gpm}-db
            REDIS_HOST: ${DOCKER_NAME:-gpm}-redis
            SANCTUM_STATEFUL_DOMAINS: localhost:${APP_PORT:-8013},127.0.0.1:${APP_PORT:-8013}
        user: ${DOCKER_USER:-501:20}

    redis:
        container_name: ${DOCKER_NAME:-gpm}-redis
        image: centos/redis-5-centos7
        ports:
            - "6379:6379"
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}

    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'

    scheduler:
        image: ${DOCKER_NAME:-gpm}-app
        container_name: ${DOCKER_NAME:-gpm}-scheduler
        entrypoint:
            - bash
            - -c
            - |-
                while true
                do
                  php artisan schedule: run --verbose --no-interaction &
                  sleep 60
                done
        volumes:
            - .:/srv/app
        environment:
            DB_HOST: ${DOCKER_NAME:-gpm}-db
            REDIS_HOST: ${DOCKER_NAME:-gpm}-redis
        user: ${DOCKER_USER:-501:20}

    queue:
        image: ${DOCKER_NAME:-gpm}-app
        container_name: ${DOCKER_NAME:-gpm}-scheduler
        entrypoint:
            - bash
            - -c
            - |-
                echo "role: queue"
                echo "SESSION_DRIVER: $SESSION_DRIVER"
                echo "CACHE_DRIVER: $CACHE_DRIVER"
                echo "QUEUE_CONNECTION: $QUEUE_CONNECTION..."
                php /srv/app/artisan queue:work --verbose --tries=3 --timeout=90
        volumes:
            - .:/srv/app
        environment:
            DB_HOST: ${DOCKER_NAME:-gpm}-db
            REDIS_HOST: ${DOCKER_NAME:-gpm}-redis
        user: ${DOCKER_USER:-501:20}

volumes:
    db:
