version: "3"
services:
    db:
        container_name: ${DOCKER_NAME:-gpm}-db
        image: mysql:8.0
        healthcheck:
            test: MYSQL_PWD=$${MYSQL_PASSWORD} mysqladmin -u $${MYSQL_USER} -h db ping
            interval: 60s
            start_period: 120s
            retries: 5
        expose:
            - "3306"
        volumes:
            - db:/var/lib/mysql
            - .docker/mysql/db-init:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_SORT_BUFFER_SIZE=256000000
            - GT_DB_DATABASE
            - GT_DB_USERNAME
            - GT_DB_PASSWORD
        user: ${DOCKER_USER:-501:20}

    app:
        image: ${DOCKER_IMAGE:-ghcr.io/clingen-data-model/cgwi-php-11.7-8.0:v1.1.3}
        container_name: ${DOCKER_NAME:-gpm}-app
        init: true
        entrypoint:
            - bash
            - /srv/app/scripts/entrypoint.sh
        depends_on:
            - db
            - redis
        expose:
            - "9000"
        links:
            - db:db
            - redis:redis
        volumes:
            - .:/srv/app
        environment:
            HOME: /srv/app
            DB_HOST: ${DOCKER_NAME:-gpm}-db
            REDIS_HOST: ${DOCKER_NAME:-gpm}-redis
            SANCTUM_STATEFUL_DOMAINS: localhost:${APP_PORT:-8013},127.0.0.1:${APP_PORT:-8013}
            XDEBUG_MODE: debug,develop
            XDEBUG_CONFIG: discover_client_host=1
        user: ${DOCKER_USER:-501:20}

    nginx:
        container_name: ${DOCKER_NAME:-gpm}-nginx
        image: ${DOCKER_IMAGE:-ghcr.io/clingen-data-model/cgwi-php-11.7-8.0:v1.1.3}
        depends_on:
            - app
        ports:
            - "${APP_PORT:-8013}:8080"
        volumes:
            - .:/srv/app
        user: ${DOCKER_USER:-501:20}
        init: true
        entrypoint:
            - /usr/sbin/nginx
            - -g
            - "daemon off;"

    redis:
        container_name: ${DOCKER_NAME:-gpm}-redis
        image: redis:alpine3.18
        expose:
            - "6379"
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        volumes:
            - redis:/var/lib/redis/data
        command:
            - /bin/sh
            - -c
            - redis-server --requirepass "$${REDIS_PASSWORD:?Need to set REDIS_PASSWORD variable}"

    mailpit:
        image: 'axllent/mailpit:latest'
        expose:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
        ports:
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8038}:8025'

    scheduler:
        image: ${DOCKER_IMAGE:-ghcr.io/clingen-data-model/cgwi-php-11.7-8.0:v1.1.3}
        container_name: ${DOCKER_NAME:-gpm}-scheduler
        depends_on:
            - app
        init: true
        entrypoint:
            - bash
            - -c
            - |-
                /srv/app/scripts/awaitdb.bash
                while true
                do
                  php artisan schedule:run --verbose --no-interaction &
                  sleep 60
                done
        volumes:
            - .:/srv/app
        environment:
            DB_HOST: ${DOCKER_NAME:-gpm}-db
            REDIS_HOST: ${DOCKER_NAME:-gpm}-redis
        user: ${DOCKER_USER:-501:20}

    queue:
        image: ${DOCKER_IMAGE:-ghcr.io/clingen-data-model/cgwi-php-11.7-8.0:v1.1.3}
        container_name: ${DOCKER_NAME:-gpm}-queue
        depends_on:
            - app
        init: true
        entrypoint:
            - bash
            - -c
            - |-
                echo "role: queue"
                echo "SESSION_DRIVER: $SESSION_DRIVER"
                echo "CACHE_DRIVER: $CACHE_DRIVER"
                echo "QUEUE_CONNECTION: $QUEUE_CONNECTION..."
                /srv/app/scripts/awaitdb.bash
                php /srv/app/artisan queue:work --verbose --tries=3 --timeout=90
        volumes:
            - .:/srv/app
        environment:
            DB_HOST: ${DOCKER_NAME:-gpm}-db
            REDIS_HOST: ${DOCKER_NAME:-gpm}-redis
        user: ${DOCKER_USER:-501:20}

volumes:
    db:
    redis:
